name: CI Workflow

on:
  push:
    branches:
      - developer-USW22
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Projenizin Node.js versiyonunu buraya yazın

      - name: Install dependencies
        run: npm install # Projenizin bağımlılıklarını yükleyin

      - name: Run tests
        run: npm test # Testlerinizi çalıştırın

      - name: Lint code
        run: npm run lint # Kodunuzu kontrol edin (eğer linting aracı kullanıyorsanız)
